name: Check
on: [pull_request, push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run prettier --check .
      - run: bun run lint
      - run: bun run test-language
